server {
    listen 80;
    server_name admin.netetfix.com;

    root /home/ubuntu/ma-commune;
    index index.php;

    location = / {
        return 302 /admin/?page=login;
    }

    location /admin/ {
        try_files $uri $uri/ /admin/index.php?$query_string;
    }

    location ~ ^/admin/.*\.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME /home/ubuntu/ma-commune$fastcgi_script_name;
        include fastcgi_params;
    }

    location / {
        return 302 /admin/?page=login;
    }
}
